language: ruby
rvm:
    - "1.9.3"
env:
    - DB=postgresql
    - DB=mysql

before_script:
    - cp config/database.travis.yml config/database.yml
    - mysql -e 'create database myapp_test'
    - psql -c 'create database myapp_test' -U postgres

script:
    - RAILS_ENV=test bundle exec rake --trace db:migrate test
    - bundle exec rake db:test:prepare
    - bundle exec rake spec

notifications:
    email: false
